AWSTemplateFormatVersion: '2010-09-09'
Description: The template used to create a ECS cluster and task using ECR image.
Parameters:
  ECSClusterName:
    Type: String
    Description: Specifies the ECS Cluster Name with which the resources would be associated
    Default: ecs1
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      ServiceConnectDefaults:
        Namespace: ecs1
      Tags: []
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Family: ecs2-server
      ContainerDefinitions:
        - Name: server
          Image: <YOUR ACCT ID>.dkr.ecr.us-east-1.amazonaws.com/ecs1:server
          Cpu: '1024'
          PortMappings:
            - Name: '9090'
              ContainerPort: 9090
              HostPort: 9090
              Protocol: tcp
              AppProtocol: http
          Essential: true
          Environment: []
          EnvironmentFiles: []
          MountPoints: []
          VolumesFrom: []
          Ulimits: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/ecs1-server
              mode: non-blocking
              awslogs-create-group: 'true'
              max-buffer-size: 25m
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs
            SecretOptions: []
          SystemControls: []
      TaskRoleArn: arn:aws:iam::<YOUR ACCT ID>:role/sam-app-upload-UploadImageRole-tf9V90jzGYcA
      ExecutionRoleArn: arn:aws:iam::<YOUR ACCT ID>:role/ecsTaskExecutionRole
      NetworkMode: awsvpc
      Volumes: []
      PlacementConstraints: []
      RequiresCompatibilities:
        - FARGATE
      Cpu: '1024'
      Memory: '3072'
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
Outputs:
  ECSCluster:
    Description: The created cluster.
    Value: !Ref ECSCluster