AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The template used for DynamoDB tables.

Parameters:
  ProjectName:
    Type: String

Resources:

  DynamoDBTableUser:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: "Delete"
    Properties:
      TableName: !Sub "${ProjectName}_user"
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "user_name"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "user_name"
      DeletionProtectionEnabled: false
      TableClass: "STANDARD"

  DynamoDBTableUserLocation:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: "Delete"
    Properties:
      TableName: !Sub "${ProjectName}_user_location"
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "user_name"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "user_name"
      DeletionProtectionEnabled: false
      TableClass: "STANDARD"

