AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The template used to create a ECS cluster and task using ECR image.

Parameters:
  ECSClusterName:
    Type: String
    Description: Specifies the ECS Cluster Name with which the resources would be associated.
    Default: ecs1
  ECSServiceName:
    Type: String
    Default: ecs1-service-sc

Resources:

  #---------------------------------------------------------------------
  # Deploys VPC
  #---------------------------------------------------------------------
  VPC:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./vpc.yml

#---------------------------------------------------------------------
# Deploy Discovery Service
#---------------------------------------------------------------------
  PrivateNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Sub ${ECSClusterName}-api-namespace
      Vpc: !GetAtt VPC.Outputs.VpcId

  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: !Sub ${ECSClusterName}-api-discovery-service
      DnsConfig:
        NamespaceId: !Ref PrivateNamespace
        DnsRecords:
          - TTL: 0
            Type: SRV

  #---------------------------------------------------------------------
  # Deploys ECS
  #---------------------------------------------------------------------
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${ECSClusterName}-upload
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:        
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
          Condition:
            ArnLike:
              aws:SourceArn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:*
            StringEquals:
              aws:SourceAccount: !Ref AWS::AccountId
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ecr-iam-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - '*'
                Sid: ''

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - FARGATE

  # Security group that limits network access to the task
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for service
      VpcId: !GetAtt VPC.Outputs.VpcId

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: !Ref ECSServiceName
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Base: 0
          Weight: 1
      TaskDefinition: !Ref "TaskDefinition"
      SchedulingStrategy: REPLICA
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref ServiceSecurityGroup]
          Subnets:  [!GetAtt "VPC.Outputs.PrivateSubnet1", !GetAtt VPC.Outputs.PrivateSubnet2]
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn   
          Port: 80
      Tags: []
      EnableECSManagedTags: true

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Family: !Sub ${ECSClusterName}-server
      ContainerDefinitions:
        - Name: server
          Image: !Sub "${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/${ECSClusterName}:upload"
          Cpu: '1024'
          PortMappings:
            - Name: 'upload'
              ContainerPort: 80
              HostPort: 80
              Protocol: tcp
              AppProtocol: http
          Essential: true
          Environment: []
          EnvironmentFiles: []
          MountPoints: []
          VolumesFrom: []
          Ulimits: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              mode: non-blocking
              max-buffer-size: 25m
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
            SecretOptions: []
          SystemControls: []
      TaskRoleArn: !Ref ECSTaskRole
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      NetworkMode: awsvpc
      Volumes: []
      PlacementConstraints: []
      RequiresCompatibilities:
        - FARGATE
      Cpu: '1024'
      Memory: '3072'
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX

  # -------------------------------------------------------------------------
  # Deploy API GW HTTP API route and integration to Cloud Map
  # -------------------------------------------------------------------------
  HttpApiSvcConnect:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: sc-HTTP-api
      Description: HTTP API Linking to Service Connect
      ProtocolType: HTTP

  APIRoute1:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApiSvcConnect
      RouteKey: 'GET /'
      Target: !Join
        - /
        - - integrations
          - !Ref APIIntegration

  APIRoute2:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApiSvcConnect
      RouteKey: 'GET /getInfo'
      Target: !Join
        - /
        - - integrations
          - !Ref APIIntegration

  APIRoute3:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApiSvcConnect
      RouteKey: 'POST /upload'
      Target: !Join
        - /
        - - integrations
          - !Ref APIIntegration

  # This security group is used by the VPC link, so that
  # you can control which resources in the VPC the VPC link is
  # allowed to communicate with.
  ApiGatewaySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for API gateway
      VpcId: !GetAtt VPC.Outputs.VpcId

  PrivateAPIGWvpcLink:  
    Type: AWS::ApiGatewayV2::VpcLink
    Properties: 
      Name: private-apigw-vpclink
      SecurityGroupIds: 
        - !Ref ApiGatewaySecurityGroup
      SubnetIds: 
        - !GetAtt "VPC.Outputs.PrivateSubnet1"
        - !GetAtt "VPC.Outputs.PrivateSubnet2"

  APIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApiSvcConnect
      Description: A Cloud Map Integration
      IntegrationType: HTTP_PROXY
      IntegrationMethod: ANY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref PrivateAPIGWvpcLink
      IntegrationUri: !GetAtt DiscoveryService.Arn
      PayloadFormatVersion: '1.0'

  # Configure the security group of the service to accept
  # inbound traffic originating from the security group of
  # the API gateway's VPC link
  ServiceIngressFromApiGateway:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow API Gateway to communicate to the service
      GroupId: !Ref ServiceSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref ApiGatewaySecurityGroup

  APILogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Sub /aws/apigateway/${ECSClusterName}
        RetentionInDays: 1

  APIStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: $default
      AutoDeploy: true
      ApiId: !Ref HttpApiSvcConnect
      AccessLogSettings:
        DestinationArn: !GetAtt APILogGroup.Arn 
        Format: '{ "requestId": "$context.requestId", "integrationErr": "$context.integrationErrorMessage", "path": "$context.path", "routeKey": "$context.routeKey", "ip": "$context.identity.sourceIp", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod","statusCode": $context.status }'      

# -------------------------------------------------------------------------
# Information about the stack.
# -------------------------------------------------------------------------
Outputs:
  APIURL:
    Description: API Gateway URL
    Value: !Sub https://${HttpApiSvcConnect}.execute-api.${AWS::Region}.amazonaws.com/ 


    