AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The template used for Lambda functions.

Parameters:
  VpcId:
    Type: String
    Description: The VPC that lambda is running inside of.
  DeploymentSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of deployment subnet ID's.
  ImageUrl:
    Type: String
    Description: The url of a docker image that contains the task application.
  LambdaSecurityGroup:
    Type: String

Resources:

  LambdaRdsConnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'RdsConnect'
      CodeUri: .
      Description: 'A Lambda To Test Connecting to RDS.'
      MemorySize: 128
      Timeout: 3
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      ImageUri: !Ref ImageUrl
      ImageConfig:
        Command:
          - lambda_function.lambda_handler
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ec2:*
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - secretsmanager:*
              Resource: '*'
      SnapStart:
        ApplyOn: None
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: !Ref DeploymentSubnetIds
        Ipv6AllowedForDualStack: false
      Events:
        Api1:
          Type: HttpApi
          Properties:
            Path: /health
            Method: get
        Api2:
          Type: HttpApi
          Properties:
            Path: /do_select
            Method: post
        Api3:
          Type: HttpApi
          Properties:
            Path: /create_schema
            Method: post
        Api4:
          Type: HttpApi
          Properties:
            Path: /insert_user
            Method: post


Outputs:
  LambdaRdsConnect:
    Description: Arn of Lambda function.
    Value: !GetAtt LambdaRdsConnect.Arn

  

