AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The template a Lambda function using Docker.

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project.
    Default: "Lambda Connecting to RDS."

Resources:

  #---------------------------------------------------------------------
  # Deploys VPC
  #---------------------------------------------------------------------
  VPC:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./vpc.yml

  #---------------------------------------------------------------------
  # Security Groups for resources.
  #---------------------------------------------------------------------
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function.
      VpcId: !GetAtt VPC.Outputs.VpcId

  # Lambda stack
  LambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambda.yaml
      Parameters:
        VpcId: !GetAtt VPC.Outputs.VpcId
        DeploymentSubnetIds: !GetAtt VPC.Outputs.PublicSubnetIds
        ImageUrl: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ecs1:lambda_rds
        LambdaSecurityGroup: !Ref LambdaSecurityGroup

# -------------------------------------------------------------------------
# Information about the stack.
# -------------------------------------------------------------------------
Outputs:
  Output1:
    Description: Meaningful outputs will go here.
    Value: TODO
