AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The template used for Lambda functions.

Parameters:
  ImageUrl:
    Type: String
    Description: The url of a docker image that contains the task application.

Resources:

  LambdaDynamoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'LambdaDynamoDBFunction'
      CodeUri: .
      Description: 'A Lambda To Test Connecting to Dynamodb.'
      MemorySize: 128
      Timeout: 10
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      ImageUri: !Ref ImageUrl
      ImageConfig:
        Command:
          - lambda_function.lambda_handler
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ec2:*
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - dynamodb:*
              Resource: '*'
      Events:
        Api1:
          Type: HttpApi
          Properties:
            Path: /health_check
            Method: get
            ApiId: !Ref LambdaApi 
        Api2:
          Type: HttpApi
          Properties:
            Path: /create_user
            Method: post
            ApiId: !Ref LambdaApi
        Api3:
          Type: HttpApi
          Properties:
            Path: /get_user
            Method: post
            ApiId: !Ref LambdaApi
        Api4:
          Type: HttpApi
          Properties:
            Path: /login
            Method: post
            ApiId: !Ref LambdaApi

  LambdaApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: API for user management.
      DefaultRouteSettings:
        ThrottlingBurstLimit: 20
        ThrottlingRateLimit: 10
      AccessLogSettings:
        DestinationArn: !GetAtt APILogGroup.Arn 
        Format: '{ "requestId": "$context.requestId", "integrationErr": "$context.integrationErrorMessage", "path": "$context.path", "routeKey": "$context.routeKey", "ip": "$context.identity.sourceIp", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod","statusCode": "$context.status" }'      

  APILogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Sub /aws/apigateway/LambdaDynamoDBFunction
        RetentionInDays: 1

Outputs:
  LambdaDynamoDBFunctionArn:
    Description: Arn of Lambda function.
    Value: !GetAtt LambdaDynamoDBFunction.Arn
  LambdaDynamoDBFunctionUrl:
    Description: "URL of the HTTP API"
    Value: !Sub https://${LambdaApi}.execute-api.${AWS::Region}.amazonaws.com 

  

