AWSTemplateFormatVersion: '2010-09-09'
Description: The template a Lambda function using Docker.


Parameters:
  ProjectName:
    Type: String
  ImageUrl:
    Type: String
    Description: The ECR url of the Docker image that contains application entry point.

Resources: 

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: IAM role for Lambdas.
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaAuth:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "DTLambdaAuth"
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUrl
      ImageConfig:
        Command:
          - lambda_function.lambda_handler_auth
      Timeout: 30
      MemorySize: 128
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512

  LambdaAuthAlways:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "DTLambdaAuthAlways"
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUrl
      ImageConfig:
        Command:
          - lambda_function.lambda_handler_auth_always
      Timeout: 30
      MemorySize: 128
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512

Outputs:
  LambdaAuthArn:
    Description: Arn of Lambda authorizer.
    Value: !GetAtt LambdaAuth.Arn
  LambdaAuthAlwaysArn:
    Description: Arn of Lambda authorizer.
    Value: !GetAtt LambdaAuthAlways.Arn


