AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The template used for Lambda functions.

Parameters:
  ProjectName:
    Type: String
  ImageUrl:
    Type: String
    Description: The url of a docker image that contains the task application.
  HTTPApiGWArn:
    Type: String
    Description: The ARN of the HTTP API Gateway.

Resources:

  LambdaDynamoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'LambdaDynamoDBFunction'
      CodeUri: .
      Description: 'A Lambda To Test Connecting to Dynamodb.'
      MemorySize: 128
      Timeout: 10
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      ImageUri: !Ref ImageUrl
      ImageConfig:
        Command:
          - lambda_function.lambda_handler
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ec2:*
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - dynamodb:*
              Resource: '*'
      Events:
        Api1:
          Type: HttpApi
          Properties:
            Path: /health_check
            Method: get
            ApiId: !Ref HTTPApiGWArn 
        Api2:
          Type: HttpApi
          Properties:
            Path: /create_user
            Method: post
            ApiId: !Ref HTTPApiGWArn
        Api3:
          Type: HttpApi
          Properties:
            Path: /get_user
            Method: post
            ApiId: !Ref HTTPApiGWArn
        Api4:
          Type: HttpApi
          Properties:
            Path: /login
            Method: post
            ApiId: !Ref HTTPApiGWArn

Outputs:
  LambdaDynamoDBFunctionArn:
    Description: Arn of Lambda function.
    Value: !GetAtt LambdaDynamoDBFunction.Arn


  

