AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The template a Lambda function using Docker.

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project.
    Default: lambda_dynamodb

Resources:

  ApiGWtack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api-gw.yaml
      Parameters:
        ProjectName: !Ref ProjectName

  LambdaStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - ApiGWtack
    Properties:
      Location: ./lambda.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ImageUrl: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ecs1:${ProjectName}
        HTTPApiGWArn: !GetAtt ApiGWtack.Outputs.HTTPApiGWArn

  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamodb.yaml
      Parameters:
        ProjectName: !Ref ProjectName

  GraphQLStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - ApiGWtack
    Properties:
      Location: ./graphql.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        HTTPApiGWArn: !GetAtt ApiGWtack.Outputs.HTTPApiGWArn

# -------------------------------------------------------------------------
# Information about the stack.
# -------------------------------------------------------------------------
Outputs:

  LambdaStackUrl:
    Description: URL of API GW.
    Value: !GetAtt ApiGWtack.Outputs.HTTPApiGWUrl

    
