AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The template a Lambda function using Docker.

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project.
    Default: DeviceTracker

Resources:

  ApiGwStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api-gw.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ImageUrl: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ecs1:${ProjectName}

  LambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambda.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ImageUrl: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ecs1:${ProjectName}

  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./dynamodb.yaml
      Parameters:
        ProjectName: !Ref ProjectName

  GraphQLStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - LambdaStack
    Properties:
      Location: ./graphql.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        HTTPApiGWAppId: !GetAtt ApiGwStack.Outputs.HTTPApiGWAppId
        AppFunctionsArn: !GetAtt ApiGwStack.Outputs.AppFunctionsArn
        LambdaAuthArn: !GetAtt LambdaStack.Outputs.LambdaAuthArn
        LambdaAuthAlwaysArn: !GetAtt LambdaStack.Outputs.LambdaAuthAlwaysArn

# -------------------------------------------------------------------------
# Information about the stack.
# -------------------------------------------------------------------------
Outputs:

  LambdaStackUrl:
    Description: URL of API GW.
    Value: !GetAtt LambdaStack.Outputs.HTTPApiGWUrl

    
