#: import dirname os.path.dirname
#: import join os.path.join

<GpsBlinker>:
    default_blink_size: 30
    blink_size: 30
    source: "transparent.png"
    opacity: 1
    
    canvas.before:
        Color:
            rgba: [0,0,255,root.opacity]
        RoundedRectangle:
            radius: [root.blink_size/2.0, ]
            size: [root.blink_size, root.blink_size]
            pos: root.pos[0] + root.size[0]/2.0 - root.blink_size/2.0, root.pos[1] + root.size[1]/2.0 - root.blink_size/2.0
