version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - PROJECT_NAME=kivy_gps_tracker # Used build path to source files.
      - ECR_REPO=ecs1                 # Name of ECR image repository.
      - DOCKER_IMAGE_NAME=tracker     # Name of Tracker Docker image.
      - DOCKER_LAMBDA_IMAGE_NAME=lambda # Name of Lambda Docker image.
      - ECR_MAIN_URI="${AWS_ACCT}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - ECR_IMG_NAME=${ECR_REPO}:${DOCKER_IMAGE_NAME}
      - ECR_LAMBDA_IMG_NAME=${ECR_REPO}:${DOCKER_LAMBDA_IMAGE_NAME}
      - ECR_IMAGE_URI=${ECR_MAIN_URI}/${ECR_REPO}:${DOCKER_IMAGE_NAME}
      - ECR_LAMBDA_IMAGE_URI=${ECR_MAIN_URI}/${ECR_REPO}:${DOCKER_LAMBDA_IMAGE_NAME}
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
      - sudo apt-get install -y qemu qemu-user-static
  build:
    commands:
      - docker build -t ${ECR_IMG_NAME} ./mobile/${PROJECT_NAME}/docker
      - aws cloudformation package --template ./mobile/${PROJECT_NAME}/cloudformation/create-app/template.yaml --s3-bucket a-unique-artifact-bucket-name --output-template-file packaged-template.yaml
      - docker buildx build --platform linux/arm64 -t ${ECR_LAMBDA_IMG_NAME} ./mobile/${PROJECT_NAME}/docker/lambda  
  post_build:
    commands:
      - docker tag ${ECR_IMG_NAME} ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}
      - docker tag ${ECR_LAMBDA_IMG_NAME} ${ECR_LAMBDA_IMAGE_URI}
      - docker push ${ECR_LAMBDA_IMAGE_URI}

artifacts:
  files:
    - packaged-template.yaml