version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - PROJECT_NAME=lambda_dynamodb      # Used build path to source files in a Git repository.
      - ECR_REPO=ecs1                     # Name of ECR image repository.
      - DOCKER_IMAGE_NAME=${PROJECT_NAME} # Name of Tracker Docker image.
      - ECR_MAIN_URI="${AWS_ACCT}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - ECR_IMG_NAME=${ECR_REPO}:${DOCKER_IMAGE_NAME}
      - ECR_IMAGE_URI=${ECR_MAIN_URI}/${ECR_REPO}:${DOCKER_IMAGE_NAME}
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
  build:
    commands:
      - docker build --platform linux/amd64 -t ${ECR_IMG_NAME} ./aws/${PROJECT_NAME}/docker  
      - aws cloudformation package --template ./aws/${PROJECT_NAME}/cloudformation/create-app/template.yaml --s3-bucket a-unique-artifact-bucket-name --output-template-file packaged-template.yaml
  post_build:
    commands:
      - docker tag ${ECR_IMG_NAME} ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}

artifacts:
  files:
    - packaged-template.yaml