version: 0.2
phases:
  pre_build:
    commands:
      - export AWS_ACCT=${AWS_ACCT}
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCT}.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - cd ./portfolio/aws/codepipeline_docker_ecs/
      - docker build -t codepipe1:latest ./docker
  post_build:
    commands:
      - docker tag codepipe1:latest ${AWS_ACCT}.dkr.ecr.${AWS_REGION}.amazonaws.com/ecs1:codepipe1
      - docker push ${AWS_ACCT}.dkr.ecr.${AWS_REGION}.amazonaws.com/ecs1:codepipe1