version: "3"
services:
  nginx:
    depends_on:
      - client
      - api  
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "9090:9090"
    volumes: 
      - /app/data
      - ./server:/app
  client:
    build: #Didn't need to break this out. Just did as an example.
      context: ./client 
      dockerfile: Dockerfile.dev
    ports:
      - "8501:8501"
    volumes: 
      - ./client:/app
    environment:
      - API_HOST=api
    depends_on:
      - api
